somosnlp/somosnlp.org

pages/index.vue

Fix to right discord invite link.

Fix discord link in index.vue

---

pages/core-team/oscar-cumbicus.md

Professor @UNL Researcher @IxaGroup

cambio mi titulo

---

pages/resources/notebook_ml_demos_con_gradio.md
pages/resources/notebook_tour_hub_huggingface.md

Agrego dos tutoriales de Hugging Face:
1. Tour del hub
2. Introducción a los demos con Gradio

Add resources from huggingface

---

pages/hackathon/index.vue

Sé que los premios no están decididos todavía pero los participantes quieren tener algo de info. Qué os parece publicar ahora algo así y después ir actualizando la página cuando corresponda?

Blog/Add info about evaluation & prizes

---

pages/hackathon/analisis-de-error-en-modelos-de-pln.md
pages/hackathon/consideraciones-de-nlp-para-lenguas-minorizadas.md
pages/hackathon/etiquetado-de-datos-para-pln.md
pages/hackathon/ia-y-pln-una-apasionante-encrucijada.md
pages/hackathon/infiriendo-topics-con-clustering-no-supervisado.md
pages/hackathon/modelos-del-lenguaje-para-redes-sociales.md
pages/hackathon/muestreo-de-datos-para-entrenamiento-de-modelos-nlp.md
pages/hackathon/recorrido-por-el-ecosistema-de-hugging-face.md
src/components/EventHackathonItem.vue

There are still TODOs and missing things (banners), but this is an initial version. Feel free to push to the branch,
The image of one of the speakers (Cristina) is huge (>2MB), we should likely compress it as well

Add initial info on speakers

---

pages/recursos/tutoriales/07_entrenamiento_finetuning.md

Realicé la traducción de training.mdx y me gustaría compartirlo en el repositorio de "somosnlp" para los tutoriales que se van a disponer en la hackathon.

Tutorial para aplicar fine-tunning a modelos pre-entrenados

---

locales/en.yml
locales/es.yml
pages/comunidad.md
pages/index.vue
pages/nuestra-mision.md

- Crear página explicando cómo contribuir a nuestra misión
- Esconder la sección de "próximos eventos"
- Actualizar la sección de "eventos anteriores"

Content / Crear una página explicando cómo contribuir 

---

locales/en.yml
locales/es.yml
pages/eventos.vue
pages/hackathon/index.vue
pages/index.vue

Feat/Anadir próximos eventos a sección "Eventos"

---

components.d.ts
locales/en.yml
locales/es.yml
pages/8m.md
pages/blog/iniciativas-8m.md
pages/hackathon/index.vue
pages/index.vue
src/components/CoreTeamList.vue
src/components/NavBar.vue
src/components/ProfileItemProps.vue
src/components/ProfileItemRouter.vue

Feat/Crear página para las iniciativas del 8M

---

pages/empleo/index.vue
pages/empleo/ofertas.ts

- msg responsabilidad
- incluir número total de ofertas
- eliminar ofertas BSC antiguas

Content/Incluir número ofertas y msg responsabilidad

---

pages/empleo/index.vue

- Relacionado al Issue #76
- Implementación de un botón para compartir la bolsa de empleo de SomosNLP en Twitter.

feat(empleo;empleo.vue):  Botón para compartir bolsa de empleo en twitter

---

pages/comunidad/david_arias.md

- Referencia al issue #129
- Resumen de cambios: 
- Nuevo perfil de contribución para la sección de comunidad.

content(pages/comunidad): perfil de contribución

---

pages/blog/nlp-de-cero-a-cien.md

content: añadir número de estudiantes

---

pages/recursos/open-source/datasets.md
pages/recursos/open-source/modelos.md
src/components/BlogPost.vue

- Referencia al issue #155 
- Modificaciones al archivo Blogpost.vue para evaluar únicamente la propiedad .tablePage (exclusiva de las páginas datasets.md y models.md).
- Modificaciones a datasets.md y models.md para incluir la nueva propiedad de frontmatter.

fix(Blogpost): Incorrecta presentación de contenido

---

pages/eventos.vue

- Referencia al issue #148
- Modificaciones a eventos.vue para incluir el hipervínculo al formulario externo.

feat(pages/eventos.vue): llamada a proyectos

---

components.d.ts
src/components/SocialMediaButtons.vue

- Referencia al Issue: #60
- Modicación a los botones de redes sociales para incluir Eventbrite.

feat: Añadir Evenbrite a SM

---

locales/en.yml
locales/es.yml
pages/[...all].vue
pages/blog/a-por-el-2023.md
pages/blog/como-contribuir.md
pages/blog/divulgacion-nlp-es.md
pages/blog/examples/proyecto-somos600m.md
pages/blog/nuestros-objetivos-para-2024.md
pages/blog/visibilidad-proyectos-comunidad.md
pages/calendario.md
pages/donatucorpus.md
pages/hackathon/index.md
pages/hackathon/patrocinios.md
pages/index.vue
pages/nuestra-mision.md
pages/recursos/datasets.md
pages/recursos/divulgacion-nlp-es.md
pages/recursos/modelos.md
pages/recursos/tutoriales/01_aplicaciones_de_los_transformers.md
pages/recursos/tutoriales/02_clasificacion_texto_amazon.md
pages/recursos/tutoriales/03_generacion_texto_rap.md
pages/recursos/tutoriales/04_traduccion_texto.md
pages/recursos/tutoriales/05_tour_hub_huggingface.md
pages/recursos/tutoriales/06_demos_con_gradio.md
pages/recursos/tutoriales/07_entrenamiento_finetuning.md
pages/recursos/wip/empresas-pln-es.md
pages/recursos/wip/tareas-de-pln.md
pages/wip.vue
src/components/ResourcesList.vue

- crear la página somosnlp.org/donatucorpus
- mejorar descripción de las actividades en la langing page
- mover las ilustraciones a una carpeta

content(hackathon): creación página dona tu corpus

---

pages/hackathon/index.en.md
pages/hackathon/patrocinios.en.md
pages/hackathon/universidades.en.md

Agrego traducción de los md faltantes en ingles

english final version

---

src/modules/pwa.ts
vite.config.ts

Attempt to fix the caching issue 🤔

chore: fix pwa

---

pages/blog/latinx-in-ai-at-naacl-2024.md
pages/comunidad/maria-grandury.md
pages/eventos.vue
pages/eventos/0-plantilla.md
pages/hackathon/bases.md
pages/hackathon/combatiendo_el_discurso_de_odio_mediante_contranarrativas.md
pages/hackathon/como_anotar_corpus_linguisticos_para_entrenar_llms.md
pages/hackathon/crear_datasets_de_calidad_con_argilla_y_distilabel.md
pages/hackathon/detecction_de_sesgos_en_medios_de_comunicacion.md
pages/hackathon/diversidad_linguistica_en_ia.md
pages/hackathon/empatia_y_emociones_en_ia.md
pages/hackathon/entrenamiento_de_llms.md
pages/hackathon/estimacion_de_la_severidad_de_la_depresion_en_internet.md
pages/hackathon/etica_ambiental_en_ia.md
pages/hackathon/ia_y_lms_retos_y_oportunidades.md
pages/hackathon/importancia_de_la_calidad_de_los_datos_al_entrenar.md
pages/hackathon/index.md
pages/hackathon/prospectiva_estrategica_y_nlp.md

- crear páginas propias eventos hackathon
- actualizar info keynotes
- añadir recursos bases hackathon
- colab latinx in ai

content(hackathon): crear paginas propias eventos hackathon

---

src/components/TableDatasetsCSV.vue

- Corrección del filtro de búsqueda para los ítems en la tabla de datasets (nombre, tarea y dominio).
- Cambio en la importación de las filas para evitar los espacios en blanco (leading/trailing whitespace).

fix(Filtro_búsqueda/TableDatasets): Corrección de bug en el filtro de búsqueda para la tabla de datasets

---

pages/recursos/modelos.md

Add Aya models to the list of Open models that support Spanish.
I added them at the beginning of the list because I assumed that it is sorted in alphabetical order. If there's a different criteria, let me know!

Update modelos.md to add Aya models

---

pages/blog/seleccion-articulos-i.md

@gonz-mart Está todo listo para publicar una vez incluyamos las imágenes :)

blog: selección artículos 1

---

pages/hackathon/bases.md

fix: enlace a proyectos 2024

---

netlify.toml

add npm flags prefix

---

components.d.ts
pages/blog/seleccion-articulos-i.md
pages/blog/seleccion-articulos-ii.md
src/components/BlogPost.vue

blog: selección artículos II

---

pages/comunidad/david_arias.md

- Actualización de información en perfil de comunidad
- Documentos con cambios: `pages/comunidad/david_arias.md`

docs(update profile.md): Update profile information

---

pages/en/hackathon-2025/index.md
pages/en/hackathon-2025/ponencias.md
pages/hackathon-2025/index.md
pages/hackathon-2025/patrocinios.md
pages/hackathon-2025/ponencias.md
src/components/CommunityList.vue

- Translate to EN
- Improve landing page intuition
- Fix details in buttons

Update info Hackathon 2025

---

pages/en/hackathon/index.md
pages/en/hackathon/patrocinios.md
pages/en/hackathon/universidades.md
pages/hackathon/patrocinios.md
pages/pt/hackathon/index.md
pages/pt/hackathon/patrocinios.md
pages/pt/hackathon/universidades.md

TODO:
- review traducciones automáticas
- traducir formularios y actualizar los enlaces

Traducir info Hackathon 2025: Portugués e Inglés
